### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by TequiLaSS** [Dawnnnnnn/-#81]
代码是不是对没有领过任何主播勋章的做判断，刚刚尝试登录后会直接抛出异常
`Traceback (most recent call last):
  File ".\run.py", line 22, in <module>
    utils.fetch_medal()
  File "E:\Sublime Text 3\program\bilibili-live-tools\utils.py", line 54, in fetch_medal
    return roomid,today_feed,day_limit
UnboundLocalError: local variable 'roomid' referenced before assignment`
![snipaste_2018-04-12_21-43-07](https://user-images.githubusercontent.com/33351660/38681321-f033e04c-3e9a-11e8-9d78-49963b2e7ac6.png)

**Comment by yjqiang** [comment]
最新版还有么
