### ISSUE TITLE
有没有对配置文件的说明啊

### ISSUE THREAD

**Issue by zuosc** [Dawnnnnnn/-#85]
搜了一圈没搜到

比如appkey和app_secret，感觉使用默认的，很容易被针对封号额。。。

还有其他参数，也不太好猜，每个配置干嘛的。。。。

**Comment by Dawnnnnnn** [comment]
appkey 好像是根据当前app的版本号来的，app_secret是一个固定值，短期不会变，其他的那些很多是根据不同的手机来的 = =

**Comment by zuosc** [comment]
@Dawnnnnnn  = =  这样啊。不过还是想知道每一个配置的大致作用.

大佬要不要考虑写个文档或者直接打个备注啥的？😉 😉

**Comment by Dawnnnnnn** [comment]
有时间就做(FLAG)
